
# Railway deployment configuration for DevX Telegram Bot
# Docs: https://docs.railway.app/deploy/configure/

[build]
  builder = "nixpacks"
  buildCommand = "echo 'No build required'"

[start]
  cmd = "npm start"